### PR TITLE
Always use error checking pthread mutex.

### LINKED ISSUE #652: Deadlock in Signal.Core send(event:) in OS X 10.11 El Capitan
I'm getting a nasty deadlock under 10.11 that seems to be leading back to `Signal.Core`. The app just hangs without any heavy loading or anything suspicious. In 10.12+ everything works as expected. 

Can you share some insights into what might be happening here? I'm guessing this is related to use of older pthread locks in pre-10.12, but not sure what goes wrong…

```
#0	0x00007fff87104de6 in __psynch_mutexwait ()
#1	0x00007fff89c33e4a in _pthread_mutex_lock_wait ()
#2	0x00000001048f9fb4 in _T013ReactiveSwift6SignalC4Core33_6DF632AE8A9288C3EAD8EFDF3D3AF99ELLC4sendyAC5EventOyxq__GF10Foundation12NotificationV_6Result7NoErrorOTg5 ()
#3	0x00000001048f8fe9 in _T013ReactiveSwift6SignalC4Core33_6DF632AE8A9288C3EAD8EFDF3D3AF99ELLC4sendyAC5EventOyxq__GF10Foundation12NotificationV_6Result7NoErrorOTg5TA ()
#4	0x00000001048f9905 in _T013ReactiveSwift0A0VAASo18NotificationCenterCRbzlE13notificationsAA6SignalCy10Foundation0C0V6Result7NoErrorOGSo14NSNotificationC4NameVSg03forL0_yXlSg6objecttFyAH8ObserverCyAkN_G_AA8LifetimeCtcfU_yAKcfU_TA ()
#5	0x00000001048f89b4 in _T010Foundation12NotificationVIegi_So14NSNotificationCIeyBy_TR ()
#6	0x00007fff97c8f8fb in -[__NSObserver _doit:] ()
#7	0x00007fff9120fbbc in __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ ()
#8	0x00007fff9120fb4f in ___CFXRegistrationPost_block_invoke ()
#9	0x00007fff9120fac7 in _CFXRegistrationPost ()
#10	0x00007fff9120f832 in ___CFXNotificationPost_block_invoke ()
#11	0x00007fff911cc5e2 in -[_CFXNotificationRegistrar find:object:observer:enumerator:] ()
#12	0x00007fff911cb835 in _CFXNotificationPost ()
#13	0x00007fff96df8a00 in -[NSView _postFrameChangeNotification] ()
#14	0x00007fff96df8793 in -[NSView setFrameOrigin:] ()
#15	0x00007fff96e0b8ea in -[NSView setFrame:] ()
#16	0x00007fff96e17f15 in -[NSView resizeWithOldSuperviewSize:] ()
#17	0x00007fff96e178a9 in -[NSView resizeSubviewsWithOldSize:] ()
#18	0x00007fff96e1a286 in NSViewLevelLayout ()
#19	0x00007fff96e1a1cb in -[NSView layout] ()
#20	0x00007fff96e813e7 in -[NSView _doLayout] ()
#21	0x00007fff96e8109f in -[NSView _layoutSubtreeWithOldSize:] ()
#22	0x00007fff96df34fb in -[NSView setFrameSize:] ()
#23	0x00007fff96e0b90d in -[NSView setFrame:] ()
#24	0x00007fff96e17f15 in -[NSView resizeWithOldSuperviewSize:] ()
#25	0x00007fff96e178a9 in -[NSView resizeSubviewsWithOldSize:] ()
#26	0x00007fff96e1a286 in NSViewLevelLayout ()
#27	0x00007fff96e1a1cb in -[NSView layout] ()
#28	0x00007fff96ea5e05 in -[NSTabView layout] ()
#29	0x00007fff96e813e7 in -[NSView _doLayout] ()
#30	0x00007fff96e8109f in -[NSView _layoutSubtreeWithOldSize:] ()
#31	0x00007fff96df34fb in -[NSView setFrameSize:] ()
#32	0x00007fff96ea5d42 in -[NSTabView setFrameSize:] ()
#33	0x00007fff96e0b90d in -[NSView setFrame:] ()
#34	0x00007fff96e17f15 in -[NSView resizeWithOldSuperviewSize:] ()
#35	0x00007fff96e178a9 in -[NSView resizeSubviewsWithOldSize:] ()
#36	0x00007fff96e1a286 in NSViewLevelLayout ()
#37	0x00007fff96e1a1cb in -[NSView layout] ()
#38	0x00007fff96e813e7 in -[NSView _doLayout] ()
#39	0x00007fff96e8109f in -[NSView _layoutSubtreeWithOldSize:] ()
#40	0x00007fff96df34fb in -[NSView setFrameSize:] ()
#41	0x00007fff96e0b90d in -[NSView setFrame:] ()
#42	0x00007fff96e17f15 in -[NSView resizeWithOldSuperviewSize:] ()
#43	0x00007fff96e178a9 in -[NSView resizeSubviewsWithOldSize:] ()
#44	0x00007fff96df3517 in -[NSView setFrameSize:] ()
#45	0x00007fff96ea02c9 in -[NSThemeFrame setFrameSize:] ()
#46	0x00007fff96e0b90d in -[NSView setFrame:] ()
#47	0x00007fff96e1821d in -[NSView resizeWithOldSuperviewSize:] ()
#48	0x00007fff96e805a8 in -[NSView layoutSubtreeIfNeeded] ()
#49	0x00007fff96e9ff21 in -[NSWindow(NSConstraintBasedLayout) _layoutViewTree] ()
#50	0x00007fff96e868e9 in -[NSWindow _setFrame:updateBorderViewSize:] ()
#51	0x00007fff96e9f379 in -[NSWindow _oldPlaceWindow:] ()
#52	0x00007fff96e9e74e in -[NSWindow _setFrameCommon:display:stashSize:] ()
#53	0x00007fff96e9dc88 in -[NSWindow _setFrame:display:allowImplicitAnimation:stashSize:] ()
#54	0x00007fff96e9dba3 in -[NSWindow setFrame:display:] ()
#55	0x00007fff96fbdb08 in -[NSWindow setFrame:display:animate:] ()
#56	0x00000001038d80e5 in _T05Gifox27PreferenceTabViewControllerC6update33_C63E23ECF9CD786E5C80AD55AED83223LLyyF ()
#57	0x00000001038d76da in _T05Gifox27PreferenceTabViewControllerC03tabD0ySo05NSTabD0C_So0gD4ItemCSg9didSelecttFyACcfU0_ ()
#58	0x0000000103aaa81e in _T013ReactiveSwift6SignalC5Gifox6Result7NoErrorORs_rlE7observeAA10Disposable_pSgqd__Sg4from_yqd__ctAA0A18ExtensionsProviderRd__lFAJqd__cfU_yqd___xtcfU_ ()
#59	0x0000000103aab492 in _T013ReactiveSwift6SignalC5Gifox6Result7NoErrorORs_rlE7observeAA10Disposable_pSgqd__Sg4from_yqd__ctAA0A18ExtensionsProviderRd__lFAJqd__cfU_yqd___xtcfU_TA ()
#60	0x0000000104826033 in _T013ReactiveSwift0A0V0A5CocoaRlzClE17makeBindingTargetAA0eF0Vyqd__GAA9Scheduler_p2on_yx_qd__tctlFyqd__cfU_TA ()
#61	0x000000010496392f in _T013ReactiveSwift13BindingTargetVACyxGAA9Scheduler_p2on_AA8LifetimeC8lifetimeyxc6actiontcfcyxcfU_yycfU_ ()
#62	0x0000000104964329 in _T013ReactiveSwift13BindingTargetVACyxGAA9Scheduler_p2on_AA8LifetimeC8lifetimeyxc6actiontcfcyxcfU_yycfU_TA ()
#63	0x000000010492b410 in _T013ReactiveSwift11UISchedulerC8scheduleAA10Disposable_pSgyycFTf4gn_n ()
#64	0x0000000104927e82 in _T013ReactiveSwift11UISchedulerCAA9SchedulerA2aDP8scheduleAA10Disposable_pSgyycFTW ()
#65	0x0000000104964255 in _T013ReactiveSwift13BindingTargetVACyxGAA9Scheduler_p2on_AA8LifetimeC8lifetimeyxc6actiontcfcyxcfU_Tf4gnn_n ()
#66	0x00000001049642c6 in _T013ReactiveSwift13BindingTargetVACyxGAA9Scheduler_p2on_AA8LifetimeC8lifetimeyxc6actiontcfcyxcfU_TA ()
#67	0x00000001048f7b52 in _T013ReactiveSwift6SignalC8ObserverCAEyxq__GyxcSg5value_yq_cSg6failedyycSg9completedAK11interruptedtcfcyAC5EventOyxq__GcfU_ ()
#68	0x00000001048f7c25 in _T013ReactiveSwift6SignalC8ObserverCAEyxq__GyxcSg5value_yq_cSg6failedyycSg9completedAK11interruptedtcfcyAC5EventOyxq__GcfU_TA ()
#69	0x00000001048f7e37 in _T013ReactiveSwift6SignalC8ObserverC4sendyAC5EventOyxq__GF ()
#70	0x00000001048fc75d in _T013ReactiveSwift6SignalC4Core33_6DF632AE8A9288C3EAD8EFDF3D3AF99ELLC4sendyAC5EventOyxq__GF ()
#71	0x0000000104919839 in _T013ReactiveSwift6SignalC4Core33_6DF632AE8A9288C3EAD8EFDF3D3AF99ELLC4sendyAC5EventOyxq__GFTA ()
#72	0x00000001048f7e37 in _T013ReactiveSwift6SignalC8ObserverC4sendyAC5EventOyxq__GF ()
#73	0x00000001048fc75d in _T013ReactiveSwift6SignalC4Core33_6DF632AE8A9288C3EAD8EFDF3D3AF99ELLC4sendyAC5EventOyxq__GF ()
#74	0x0000000104919839 in _T013ReactiveSwift6SignalC4Core33_6DF632AE8A9288C3EAD8EFDF3D3AF99ELLC4sendyAC5EventOyxq__GFTA ()
#75	0x00000001048f7e37 in _T013ReactiveSwift6SignalC8ObserverC4sendyAC5EventOyxq__GF ()
#76	0x00000001048fc75d in _T013ReactiveSwift6SignalC4Core33_6DF632AE8A9288C3EAD8EFDF3D3AF99ELLC4sendyAC5EventOyxq__GF ()
#77	0x0000000104919839 in _T013ReactiveSwift6SignalC4Core33_6DF632AE8A9288C3EAD8EFDF3D3AF99ELLC4sendyAC5EventOyxq__GFTA ()
#78	0x00000001048f7e37 in _T013ReactiveSwift6SignalC8ObserverC4sendyAC5EventOyxq__GF ()
#79	0x00000001048fc75d in _T013ReactiveSwift6SignalC4Core33_6DF632AE8A9288C3EAD8EFDF3D3AF99ELLC4sendyAC5EventOyxq__GF ()
#80	0x0000000104919839 in _T013ReactiveSwift6SignalC4Core33_6DF632AE8A9288C3EAD8EFDF3D3AF99ELLC4sendyAC5EventOyxq__GFTA ()
#81	0x00000001048f8607 in _T013ReactiveSwift6SignalC8ObserverC4sendyAC5EventOyxq__GFTA ()
#82	0x00000001048e7280 in _T013ReactiveSwift6SignalC5EventO11skipRepeatsyAEyxq__GcyAGc_AA8LifetimeCtcSbx_xtcFZyAGcyAGc_AItcfU_yAGcfU_ ()
#83	0x00000001048ed97d in _T013ReactiveSwift6SignalC5EventO4skipyAEyxq__GcyAGc_AA8LifetimeCtcSbxc5while_tFZyAGcyAGc_AItcfU_yAGcfU_TATm ()
#84	0x00000001048ed940 in _T013ReactiveSwift6SignalC5EventO11skipRepeatsyAEyxq__GcyAGc_AA8LifetimeCtcSbx_xtcFZyAGcyAGc_AItcfU_yAGcfU_TA ()
#85	0x00000001048f7e37 in _T013ReactiveSwift6SignalC8ObserverC4sendyAC5EventOyxq__GF ()
#86	0x00000001048fc75d in _T013ReactiveSwift6SignalC4Core33_6DF632AE8A9288C3EAD8EFDF3D3AF99ELLC4sendyAC5EventOyxq__GF ()
#87	0x0000000104919839 in _T013ReactiveSwift6SignalC4Core33_6DF632AE8A9288C3EAD8EFDF3D3AF99ELLC4sendyAC5EventOyxq__GFTA ()
#88	0x00000001048f8607 in _T013ReactiveSwift6SignalC8ObserverC4sendyAC5EventOyxq__GFTA ()
#89	0x00000001048e457b in _T013ReactiveSwift6SignalC5EventO9filterMapyAEyxq__GcyAEyqd__q__Gc_AA8LifetimeCtcqd__SgxclFZyAGcyAHc_AJtcfU_yAGcfU_ ()
#90	0x00000001048eb90d in _T013ReactiveSwift6SignalC5EventO9filterMapyAEyxq__GcyAEyqd__q__Gc_AA8LifetimeCtcqd__SgxclFZyAGcyAHc_AJtcfU_yAGcfU_TATm ()
#91	0x00000001048eb7c0 in _T013ReactiveSwift6SignalC5EventO9filterMapyAEyxq__GcyAEyqd__q__Gc_AA8LifetimeCtcqd__SgxclFZyAGcyAHc_AJtcfU_yAGcfU_TA ()
#92	0x00000001048f7e37 in _T013ReactiveSwift6SignalC8ObserverC4sendyAC5EventOyxq__GF ()
#93	0x00000001048fc75d in _T013ReactiveSwift6SignalC4Core33_6DF632AE8A9288C3EAD8EFDF3D3AF99ELLC4sendyAC5EventOyxq__GF ()
#94	0x0000000104919839 in _T013ReactiveSwift6SignalC4Core33_6DF632AE8A9288C3EAD8EFDF3D3AF99ELLC4sendyAC5EventOyxq__GFTA ()
#95	0x00000001048f7e37 in _T013ReactiveSwift6SignalC8ObserverC4sendyAC5EventOyxq__GF ()
#96	0x00000001048fc75d in _T013ReactiveSwift6SignalC4Core33_6DF632AE8A9288C3EAD8EFDF3D3AF99ELLC4sendyAC5EventOyxq__GF ()
#97	0x0000000104919839 in _T013ReactiveSwift6SignalC4Core33_6DF632AE8A9288C3EAD8EFDF3D3AF99ELLC4sendyAC5EventOyxq__GFTA ()
#98	0x00000001048fa203 in _T013ReactiveSwift6SignalC4Core33_6DF632AE8A9288C3EAD8EFDF3D3AF99ELLC4sendyAC5EventOyxq__GF10Foundation12NotificationV_6Result7NoErrorOTg5 ()
#99	0x00000001048f8fe9 in _T013ReactiveSwift6SignalC4Core33_6DF632AE8A9288C3EAD8EFDF3D3AF99ELLC4sendyAC5EventOyxq__GF10Foundation12NotificationV_6Result7NoErrorOTg5TA ()
#100	0x00000001048f9905 in _T013ReactiveSwift0A0VAASo18NotificationCenterCRbzlE13notificationsAA6SignalCy10Foundation0C0V6Result7NoErrorOGSo14NSNotificationC4NameVSg03forL0_yXlSg6objecttFyAH8ObserverCyAkN_G_AA8LifetimeCtcfU_yAKcfU_TA ()
#101	0x00000001048f89b4 in _T010Foundation12NotificationVIegi_So14NSNotificationCIeyBy_TR ()
#102	0x00007fff97c8f8fb in -[__NSObserver _doit:] ()
#103	0x00007fff9120fbbc in __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ ()
#104	0x00007fff9120fb4f in ___CFXRegistrationPost_block_invoke ()
#105	0x00007fff9120fac7 in _CFXRegistrationPost ()
#106	0x00007fff9120f832 in ___CFXNotificationPost_block_invoke ()
#107	0x00007fff911cc5e2 in -[_CFXNotificationRegistrar find:object:observer:enumerator:] ()
#108	0x00007fff911cb835 in _CFXNotificationPost ()
#109	0x00007fff96df8a00 in -[NSView _postFrameChangeNotification] ()
#110	0x00007fff96df36d3 in -[NSView setFrameSize:] ()
#111	0x00007fff96e0b90d in -[NSView setFrame:] ()
#112	0x00007fff96e17f15 in -[NSView resizeWithOldSuperviewSize:] ()
#113	0x00007fff96e178a9 in -[NSView resizeSubviewsWithOldSize:] ()
#114	0x00007fff96e1a286 in NSViewLevelLayout ()
#115	0x00007fff96e1a1cb in -[NSView layout] ()
#116	0x00007fff96e813e7 in -[NSView _doLayout] ()
#117	0x00007fff96e8109f in -[NSView _layoutSubtreeWithOldSize:] ()
#118	0x00007fff96e805d8 in -[NSView layoutSubtreeIfNeeded] ()
#119	0x00007fff96e7ffc1 in -[NSView _setDefaultKeyViewLoop] ()
#120	0x00007fff96e8c07c in -[NSTabViewItem _setDefaultKeyViewLoopAndInitialFirstResponder] ()
#121	0x00007fff96e8bfff in -[NSTabView _switchInitialFirstResponder:lastKeyView:forTabViewItem:] ()
#122	0x00007fff911fb5b5 in -[NSArray makeObjectsPerformSelector:withObject:] ()
#123	0x00007fff97027907 in -[NSTabView _finishedMakingConnections] ()
#124	0x00007fff911facef in -[NSSet makeObjectsPerformSelector:] ()
#125	0x00007fff96d98df9 in -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] ()
#126	0x00007fff96ea95a7 in -[NSNib _instantiateNibWithExternalNameTable:options:] ()
#127	0x00007fff96ea91f7 in -[NSNib _instantiateWithOwner:options:topLevelObjects:] ()
#128	0x00007fff97510c9e in -[NSStoryboard instantiateControllerWithIdentifier:] ()
#129	0x000000010396ff5b in _T05Gifox20StoryboardControllerPAAE9constructxSo12NSStoryboardC4from_Sb4loadtFZ ()
#130	0x000000010397084d in _T05Gifox30PreferenceStoryboardControllerPAAE9constructxSb4load_tFZ ()
#131	0x000000010397717e in _T05Gifox11ApplicationC15showPreferencesySo10NSMenuItemCF ()
#132	0x000000010397720c in _T05Gifox11ApplicationC15showPreferencesySo10NSMenuItemCFTo ()
#133	0x00007fff928d607a in _os_activity_initiate ()
#134	0x00007fff97035dbd in -[NSApplication sendAction:to:from:] ()
#135	0x00007fff97047f12 in -[NSControl sendAction:to:] ()
#136	0x00007fff97047e3c in __26-[NSCell _sendActionFrom:]_block_invoke ()
#137	0x00007fff928d607a in _os_activity_initiate ()
#138	0x00007fff97047d99 in -[NSCell _sendActionFrom:] ()
#139	0x00007fff928d607a in _os_activity_initiate ()
#140	0x00007fff970463be in -[NSCell trackMouse:inRect:ofView:untilMouseUp:] ()
#141	0x00007fff9708ef04 in -[NSButtonCell trackMouse:inRect:ofView:untilMouseUp:] ()
#142	0x00007fff97044ae8 in -[NSControl mouseDown:] ()
#143	0x00007fff975993c9 in -[NSWindow _handleMouseDownEvent:isDelayedEvent:] ()
#144	0x00007fff9759a3ad in -[NSWindow _reallySendEvent:isDelayedEvent:] ()
#145	0x00007fff96fd9539 in -[NSWindow sendEvent:] ()
#146	0x00007fff96f59a38 in -[NSApplication sendEvent:] ()
#147	0x00000001038a1aeb in _T05Gifox11ApplicationC9sendEventySo7NSEventCF ()
#148	0x00000001038a1e7c in _T05Gifox11ApplicationC9sendEventySo7NSEventCFTo ()
#149	0x00007fff96dc0df2 in -[NSApplication run] ()
```

### PR DESCRIPTION
**Pull request by andersio**
Resolves #652 and https://github.com/ReactiveCocoa/ReactiveCocoa/issues/3598.

Make all `Lock.PthreadLock` be backed by error checking mutexes. Mitigate #508 in a different way.

#### Checklist
- [ ] Updated CHANGELOG.md.

### CODE REVIEW

File: Sources/Atomic.swift [hunk 1]
```diff
@@ -187,6 +181,15 @@ internal class Lock {
 			case EBUSY:
 				return false
 			default:
+				#if DEBUG && arch(arm)
```
Comment (brow) [inline Sources/Atomic.swift]: It looks like `EAGAIN` will be silently allowed when `DEBUG`, but will lead to an assertion failure when `!DEBUG`.

I wonder if it should be the other way around? I usually set `DEBUG` in builds where I want _more_ assertions.

Comment (andersio) [reply Sources/Atomic.swift]: I guess at this point we should just treat `EAGAIN` as `EBUSY`. Just found this issue: https://github.com/ReactiveCocoa/ReactiveCocoa/issues/3598.

Comment (andersio) [reply Sources/Atomic.swift]: The weirdest thing is that based on [the libpthread implementation](https://opensource.apple.com/source/libpthread/libpthread-301.30.1/src/pthread_mutex.c.auto.html) only the recursive lock can return `EAGAIN`, and it holds for implementations since El Capitan GM. All the reported issues do not seem to involve properties which are the only thing using recursive locks in ReactiveSwift.
